{
 "title": "Monitoring Golden Signals for Kubernetes",
 "description": "This comprehensive Grafana dashboard provides a detailed view of the key metrics categorized under the Four Golden Signals: Latency, Traffic, Errors, and Saturation. Designed for quick issue identification, this dashboard offers real-time insights into the performance and health of your Kubernetes cluster. Ideal for DevOps teams and SREs, this dashboard is your go-to resource for proactive Kubernetes cluster management.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incoming Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"source\"}[1m])), 0.001)",
     "legendFormat": "Incoming Traffic"
    }
   ]
  },
  {
   "title": "Istio Incoming Traffic",
   "type": "stat",
   "description": "Istio incoming RPS",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"source\"}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Global Success Rate (non-5xx responses)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"source\", response_code!~\"5.*\"}[1m])) / sum(rate(istio_requests_total{reporter=\"source\"}[1m]))"
    }
   ]
  },
  {
   "title": "CoreDNS Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "CoreDNS Requests (by qtype)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "API server Work Queue Add Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"apiserver\", instance=~\".*\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "API server total requests verb",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (verb) (rate(apiserver_request_total[5m]))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "API Server RPC Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"apiserver\", instance=~\".*\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{job=\"apiserver\", instance=~\".*\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{job=\"apiserver\", instance=~\".*\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{job=\"apiserver\", instance=~\".*\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "API server total requests code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(apiserver_request_total[5m]))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Node Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{node=~\".*\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{node=~\".*\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance, device)(rate(node_network_receive_bytes_total[$__rate_interval])*8)",
     "legendFormat": "recv {{instance}} {{device}}"
    },
    {
     "expr": "sum by (instance, device)(rate(node_network_transmit_bytes_total[$__rate_interval])*8)",
     "legendFormat": "trans {{instance}} {{device}}"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Node Count",
   "type": "stat",
   "description": "Number of nodes active in cluster.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_node_labels{node=~\".*\"})"
    }
   ]
  },
  {
   "title": "Namespaces ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": " count(kube_namespace_created)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "PVCs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cluster CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100))"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (100 - ((node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100)\r\n"
    }
   ]
  },
  {
   "title": "Pods with highest CPU",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "mCore" } },
   "targets": [
    {
     "expr": "topk(10, sum by (pod) (irate(container_cpu_usage_seconds_total{container=\"\", cpu=\"total\", name=\"\"}[5m]) * 1000))"
    }
   ]
  },
  {
   "title": "Pods with highest Memory",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "topk(10, sum by (pod) (container_memory_working_set_bytes{container=\"\", name=\"\"} / 1000000000))"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "timeseries",
   "description": "Number of nodes active in the cluster",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_node_labels{node=~\".*\"})",
     "legendFormat": "Node Count"
    }
   ]
  },
  {
   "title": "Total pod count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "count(kube_pod_info)", "legendFormat": "total count" }
   ]
  },
  {
   "title": "Nodes with highest CPU utilization",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "topk(10, 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100))"
    }
   ]
  },
  {
   "title": "Nodes with highest Memory utilization",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "topk(10, 100 - ((node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100)\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_filefd_maximum{jobLabel!=\"node-exporter\"})",
     "legendFormat": "Max open files"
    },
    {
     "expr": "topk (10, sum by (instance) (node_filefd_allocated{container=\"node-exporter\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sockstat Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk (10, sum by (instance) (node_sockstat_sockets_used{container=\"node-exporter\"}))",
     "legendFormat": "Sockets_used - Sockets currently in use - {{instance}}"
    }
   ]
  },
  {
   "title": "NF Contrack",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk (10, sum by (instance) (node_nf_conntrack_entries{container=\"node-exporter\"}))",
     "legendFormat": "NF conntrack entries - {{instance}}"
    },
    {
     "expr": "avg(node_nf_conntrack_entries_limit{container=\"node-exporter\"})",
     "legendFormat": "NF conntrack limit"
    }
   ]
  },
  {
   "title": "Persistent Volume Claim",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum by (persistentvolumeclaim,namespace,storageclass,volumename) (kube_persistentvolumeclaim_info{namespace=~\".*\"})"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=~\".*\"}/1024/1024/1024)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\".*\"}/1024/1024/1024)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace=~\".*\"}/1024/1024/1024)"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=~\".*\",phase=~\"(Pending|Lost)\"}) by (persistentvolumeclaim) + sum(kube_persistentvolumeclaim_status_phase{namespace=~\".*\",phase=~\"(Lost)\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\".*\"}/kubelet_volume_stats_capacity_bytes{namespace=~\".*\"} * 100)"
    }
   ]
  },
  {
   "title": "Storage Class",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 81 },
   "targets": [
    { "expr": "kube_storageclass_info" }
   ]
  },
  {
   "title": "Hourly Volume Usage Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes{namespace=~\".*\"}[1h])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "All Running PVCs Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\".*\"}))",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_job_status_succeeded{namespace=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\".*\"})"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace,container) (rate(container_cpu_cfs_throttled_periods_total{container!=\"istio-proxy\"}[5m]))",
     "legendFormat": "{{namespace}}-{{container}}"
    }
   ]
  },
  {
   "title": "CoreDNS Cache (Misses)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_misses_total[1m]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Pods not in Running state by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_status_phase{phase=\"Failed\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts{namespace=\"kube-system\"}[30m]))"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Nodes with MemoryPressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", status=\"true\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Nodes Out of Disk",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes with DiskPressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", status=\"true\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\".*\"})"
    }
   ]
  },
  {
   "title": "PVCs in Lost State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{namespace=~\"${k8s_namespace}\",phase=\"Lost\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "PVCs in Pending State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{namespace=~\"${k8s_namespace}\",phase=\"Pending\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "PVCs Above Warning Threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\".*\"} ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\".*\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{namespace=~\".*\"} )) >= (80 / 100)) or vector (0)"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (instance,device) (irate(node_network_receive_errs_total{}[5m]))",
     "legendFormat": "{{instance}} - {{device}} - Receive errors"
    },
    {
     "expr": "sum by (instance,device) (irate(node_network_transmit_errs_total{}[5m]))",
     "legendFormat": "{{instance}} - {{device}} - Rransmit errors"
    }
   ]
  },
  {
   "title": "API server errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum\n  by(verb) (rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\"}[5m]))\n  / sum by(verb) (rate(apiserver_request_total{job=\"apiserver\"}[5m]))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Kubelet Operation Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_errors_total{}[5m])) by (operation_type)",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "Pod Start Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_pod_start_duration_seconds_bucket{}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pod startup latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " histogram_quantile(0.99,\n  sum by(instance, le) (rate(kubelet_pod_worker_duration_seconds_bucket{job=\"kubelet\",metrics_path=\"/metrics\"}[5m])))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"}",
     "legendFormat": "{{node}} "
    }
   ]
  },
  {
   "title": "CoreDNS Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(rate(coredns_dns_request_duration_seconds_bucket{}[5m]))",
     "legendFormat": "max delay"
    }
   ]
  },
  {
   "title": "API server Work Queue Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"apiserver\", instance=~\".*\"}[5m])) by (instance, name, le))"
    }
   ]
  },
  {
   "title": "API Server Work Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{job=\"apiserver\", instance=~\".*\"}[5m])) by (instance, name)"
    }
   ]
  },
  {
   "title": "API server Request duration 99th quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\", instance=~\".*\"}[5m])) by (verb, le))"
    }
   ]
  },
  {
   "title": "ETCD Cache Duration 99th Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(etcd_request_duration_seconds_bucket{job=\"apiserver\",instance=~\".*\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} get"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(etcd_request_duration_seconds_bucket{job=\"apiserver\",instance=~\".*\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} miss"
    }
   ]
  },
  {
   "title": "Traffic ( for Nginx Ingress Controller)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 177 }
  },
  {
   "title": "Controller Request Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{controller_pod=~\"All\",controller_class=~\"All\",namespace=~\"All\"}[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "Controller Success Rate (non-4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_pod=~\"All\",controller_class=~\"All\",namespace=~\"All\",status!~\"[4-5].*\"}[2m])) / sum(rate(nginx_ingress_controller_requests{controller_pod=~\"All\",controller_class=~\"All\",namespace=~\"All\"}[2m]))"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{controller_pod=~\"All\",controller_class=~\"All\",controller_namespace=~\"All\"}[2m]))"
    }
   ]
  },
  {
   "title": "Ingress Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{controller_pod=~\"All\",controller_class=~\"All\",controller_namespace=~\"All\",ingress=~\"All\"}[2m])) by (ingress), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_pod=~\"All\",controller_class=~\"All\",namespace=~\"All\",ingress=~\"All\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{controller_pod=~\"All\",controller_class=~\"All\",namespace=~\"All\",ingress=~\"All\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  }
 ]
}