name: Build raw-kproducer image

on:
#  push:
#    paths:
#      - KafkaExample.Shared/**
#      - KafkaExample.RawDataProducer/**
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          cache: true
          cache-dependency-path: "KafkaExample.RawDataProducer/packages.lock.json"

      - name: Set environment variables
        id: set-variables
        run: |
          echo "VERSION=$(grep -oP '<ContainerImageTags>\K[^;]+' KafkaExample.RawDataProducer/KafkaExample.RawDataProducer.csproj)" >> "$GITHUB_OUTPUT"

      - name: Build raw-kproducer
        run: dotnet publish KafkaExample.RawDataProducer --os linux --arch x64 -c Release /t:PublishContainer

      - name: Tag image
        run: |
          docker tag raw-kproducer:${{ steps.set-variables.outputs.VERSION }} ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/raw-kproducer:${{ steps.set-variables.outputs.VERSION }}
          docker tag raw-kproducer:latest ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/raw-kproducer:latest

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push
        run: docker push -a ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/raw-kproducer
