name: Build raw-kconsumer chart

on:
#  push:
#    paths:
#      - manifests/raw-kconsumer/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment variables
        id: set-variables
        run: |
          echo "VERSION=$(yq -r .version manifests/raw-kconsumer/Chart.yaml)" >> "$GITHUB_OUTPUT"

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Helm package
        run: helm package manifests/raw-kconsumer --dependency-update

      - name: Helm publish
        run: helm push raw-kconsumer-${{ steps.set-variables.outputs.VERSION }}.tgz oci://${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}
