name: Build processed-kconsumer image

on:
#  push:
#    paths:
#      - KafkaExample.Shared/**
#      - KafkaExample.ProcessedDataConsumer/**
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          cache: true
          cache-dependency-path: "KafkaExample.ProcessedDataConsumer/packages.lock.json"

      - name: Set environment variables
        id: set-variables
        run: |
          echo "VERSION=$(grep -oP '<ContainerImageTags>\K[^;]+' KafkaExample.ProcessedDataConsumer/KafkaExample.ProcessedDataConsumer.csproj)" >> "$GITHUB_OUTPUT"

      - name: Build processed-kconsumer
        run: dotnet publish KafkaExample.ProcessedDataConsumer --os linux --arch x64 -c Release /t:PublishContainer

      - name: Tag image
        run: |
          docker tag processed-kconsumer:${{ steps.set-variables.outputs.VERSION }} ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/processed-kconsumer:${{ steps.set-variables.outputs.VERSION }}
          docker tag processed-kconsumer:latest ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/processed-kconsumer:latest

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push
        run: docker push -a ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/processed-kconsumer
